name: Go (posix-pattern)

on:
  push:
    branches: [ main ]
  pull_request:

permissions: {}

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/basic_go.yml@abb79c974d34c0ec6cda3bcfcb2edb6679d197e1
    permissions:
      contents: read
      packages: read
      # To report Github Actions status checks
      statuses: write
