name: Go (posix-pattern)

on:
  push:
    branches: [ main ]
  pull_request:

permissions: {}

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/basic_go.yml@188e554c08d0fbb4683027783ac7d13de5ae9e7f
    permissions:
      contents: read
      packages: read
      # To report Github Actions status checks
      statuses: write
